language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support
    - extra-google-gcm
    - extra-google-m2repository
    - extra-google-google_play_services

script: ./gradlew build